version: 2

sources:
  # - name: axis_core
  #   database: Ssot
  #   tables:
  #     - name: walletdetails
  #     - name: transactiondetails
        
  - name: axis_sme
    # database: dbt
    tables:
      - name: clients
      - name: clientemployees
      - name: disbursementtransactions
      - name: bankpaymenttransactions
      - name: bankpayments

  - name: dbt-dimensions
    tables:
      - name: clients_dimension
      - name: clients_stagging
      - name: clients_stagging_2
      - name: employees_dimension
      - name: employees_stagging
      - name: employees_stagging_2


