version: 2

sources:
        
  - name: axis_sme
    tables:
      - name: clients
      - name: clientemployees
      - name: disbursementtransactions
      - name: bankpaymenttransactions
      - name: bankpayments

  - name: dbt-dimensions
    tables:
      - name: inc_clients_dimension
      - name: inc_clients_stagging
      - name: inc_clients_stagging_2
      - name: inc_employees_dimension
      - name: inc_employees_stagging
      - name: inc_employees_stagging_2


